# -*- coding: utf-8 -*-
"""crazy_code2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jtu87aP2MbjpABjGcNRyVYC7VNbKQ8cu

# *“*SOMEBODY TOLD ME I’M A FAILURE, I’LL PROVE THEM WRONG.” – NARUTO
"""

#Qr code generation using any link of png
!pip install pyqrcode
!pip install pillow
!pip install pypng

import pyqrcode
from PIL import Image
import png

a = input("Enter any URL to create a QRCODE: ")
qr = pyqrcode.create(a)
qr.png("QRCode.png", scale = 3)
Image.open("QRCode.png")

