# -*- coding: utf-8 -*-
"""python_dsa_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKZwzu97DHR9yOHVKl-MW663B7lvEN1D
"""

from collections import namedtuple

a = namedtuple('cloth', ['Type','size','frequency'])
b = a('jeans','xxl','4')

print('using index of the size:' + b[1])

print("using index of the frequency: " + b[2])

print("using key of the type: " + b.Type )

# deque
from collections import deque
a = deque()
print(a)
b = deque([1,3,'ML Naruto'])
print(b)

b.append('Machine Learning')
print(b)

b.pop() # pop means to delete the last item of the list
print(b)

b.pop()
print(b)

b.appendleft('Itachi uchiha')
print(b)

b.popleft()
print(b)

# ordered dictionary

from collections import OrderedDict
a = OrderedDict({'Name':1, 'age': 6, 'Salary': 50000})
a['Location'] = 'Bangalore'
print(a)

print(a)

# Default dict
from collections import defaultdict
a = defaultdict(int)

b = str.split("science social maths science maths english hindi social")

for i in b:
  a[i] += 1
print(a)

# if you try this on the built in dictionary class, you will definitely get "Key error"

# chainmap

from collections import ChainMap

dict1 = {'Name':1, 'age': 2}
dict2 = {'salary':3, 'location': 4}
dict3 = {'height':5, 'hobbies': 6}

chain = ChainMap(dict1,dict2,dict3)
print(chain)

print(list(chain.keys()))

print(list(chain.values()))

print(chain['salary'])
print(chain['location'])

# counter 
from collections import Counter

a = Counter('lollypop')
print(a['p'])
print(a['l'])

# userdict

from collections import UserDict
class Mydict(UserDict):
  def push(self, key, value):
    raise RuntimeError("Cannot insert")

a = Mydict({'Name':1, 'age': 2, 'salary': 3})
a.push('location', 4)

# push function is nothing but a customized function in our mydict class to add customized functionality 
# it doesnot allow us to insert any element into dictionary

# userlist
from collections import UserList
class Mylist(UserList):
  def push(self, key):
    raise RuntimeError("cannot insert in the list")

a = Mylist([1,5,98])
a.push(900)

# userstring
from collections import UserString
class Mystring(UserString):
  def append(self, value):
    self.data += value

s1 = Mystring("virat")
print("original string: ", s1)
s1.append(' kohli')
print("After appending: ", s1)

#we are actually customizing the functionalities for respective objecs (userlist for lists, userdicts for dict, userstring for strings)